### ISSUE TITLE
The command `ftcli converter vf2i <fontfile> -s` doesn't ask for the `wdth` axis?

### ISSUE THREAD

**Issue by nero-0** [ftCLI/ftCLI#212]
Hey.
As stated in the title, why does it not ask for the `wdth` value when using the `-s` option with the `ftcli converter vf2i` command?

Also, thanks for this amazing tool!

**Comment by ftCLI** [comment]
The font has a `wdth` axis? You can check it with ` ftcli print vf-instances <path>`

**Comment by ftCLI** [comment]
Done: https://github.com/ftCLI/FoundryTools-CLI/releases/tag/v1.1.22

No need to pass `-h`, hidden axes are always printed.

**Comment by ftCLI** [comment]
I removed it in v2. I'll add it again in the next release
