### ISSUE TITLE
Bump python version requirements

### ISSUE THREAD

**Issue by nask0** [ftCLI/ftCLI#43]
Hello there,
I was just about to open PR for bumping the Python version, since the current, at least on Fedora is `3.11.3` and therefore do not satisfy `<3.11`, but I just saw that it is already fixed [here](https://github.com/ftCLI/ftCLI/compare/main...colinmford:ftCLI:main) so I guess there is no need :)

Cheers,
nask0

**Comment by ftCLI** [comment]
Hi,

the problem with Python 3.11 is that afdko still doesn’t support it. At least on Windows, you won’t be able to install.

**Comment by ftCLI** [comment]
“The AFDKO requires [Python](http://www.python.org/download) 3.8 or later. Regarding Python 3.11: while Python 3.11 itself is now relatively stable, we are waiting to let some known tool-chain problems resolve.”

https://pypi.org/project/afdko/

**Comment by nask0** [comment]
I see, thanks. Well, I cannot test in on Windows, but on Linux and Python 3.11 / afdko 3.9.5 everything works perfectly - I was able to test every single functionality. This is the only change I had to apply:
```
-    python_requires=">=3.7, <3.11",
+    python_requires=">=3.7, ~=3.11",
```
so I'm good :)

Anyway, thanks for the great tool, it was invaluable for me today, cheers.
